### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by reesercollins** [JoshPiper/GModStore-Deployment#18]
Got the following error in my action. It didn't make the action fail, but my file didn't upload.

```
Run JoshPiper/GModStore-Deployment@v0.6.0
(node:2271) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/home/runner/work/_actions/JoshPiper/GModStore-Deployment/v0.6.0/dist/index.js:1397:40)
    at FormData._multiPartHeader (/home/runner/work/_actions/JoshPiper/GModStore-Deployment/v0.6.0/dist/index.js:1348:33)
    at FormData.append (/home/runner/work/_actions/JoshPiper/GModStore-Deployment/v0.6.0/dist/index.js:1241:21)
    at main (/home/runner/work/_actions/JoshPiper/GModStore-Deployment/v0.6.0/dist/index.js:3760:13)
(node:2271) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2271) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.****
```

Seems to be caused by `newVersion.append("name", version)`

**Comment by JoshPiper** [comment]
For some reason, the form data isn't reading the file?

**Comment by reesercollins** [comment]
My input for version was `1.0.2-private` which seems to be parsed out correctly. Possibly an issue with the array destructuring?

**Comment by JoshPiper** [comment]
Seems to be an issue with the destructuring, as
```js
const versionParse = getVersion(versionStr)
[version, type] = versionParse
```
is failing, despite versionParse being a 2 length array.
